In [32]:
import keras
import numpy as np
from sklearn.datasets import load_iris
dataset=load_iris()
##How data looks like?
print(dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [33]:
##Step : 1 : Know the data
print(type(dataset))
print(len(dataset))
#Dataset is in bunch format. Bunch is a dictionary like object.
print(dataset.keys())
#We try to find out what values are stored in these attributes
print(dataset['data'][0:5])
print(dataset['target'][0:5])
print(dataset['target_names'][0:5])
print(dataset['DESCR'])
print(dataset['feature_names'])
print(dataset['filename'])
#Next we define our x and y; y is the dependent on x
x=dataset['data']
print(len(x)) #To check length of dataset
y=dataset['target']
print(len(y)) #To check length of targets
print(x[0])
print(y[0])

<class 'sklearn.utils._bunch.Bunch'>
8
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ==============

In [34]:
# Step 2: Convert y into one hot encoded vector
# One hot encoding is used because Y has labels (0, 1, 2) - which is categorical data with no ordinal relationships
from keras.utils import to_categorical
Ny = len(np.unique(y))
print(Ny)
Y = to_categorical(y, num_classes=Ny)
print(Y[0:5])


3
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [35]:
##Step : 3 : Now we split the data into two parts - one for training another for testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.10,shuffle=True)
print(x_train[0:5])
print(x_test[0:5])
print(y_train[0:5])
print(y_test[0:5])

[[5.2 3.5 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.6 2.5 3.9 1.1]
 [5.  3.  1.6 0.2]
 [4.9 3.1 1.5 0.2]]
[[5.1 3.3 1.7 0.5]
 [6.5 3.  5.5 1.8]
 [5.2 4.1 1.5 0.1]
 [7.7 2.8 6.7 2. ]
 [6.5 3.  5.8 2.2]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [36]:
##Step : 4 : Then we normalize the data
from sklearn.preprocessing import StandardScaler
##Normalization is done so that the difference between highest and lowest data point is not too large
import numpy as np
scaler=StandardScaler()
##To find mean and std dev
scaler.fit(x_train)

##Converting data into form where mean of data is 0 and std dev is 1
X_train=scaler.transform(x_train)
X_test=scaler.transform(x_test)
print(np.amax(X_train,axis=0))
print(np.amin(X_train,axis=0))

[2.5039451  3.03730129 1.81657213 1.72810075]
[-1.82980604 -2.36976255 -1.54440278 -1.42451548]


In [37]:
##Step : 5 : Now finally we build the model using keras
!pip install tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(20, input_dim=X_train.shape[1], activation='relu'))
##Dropout is used to avoid overfitting
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
##For classification problems, we usually use softmax as activation function in final layer
model.add(Dense(3, activation='softmax'))
##Compiling the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [38]:
##Step : 6 : Know the model
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_11 (Dense)            (None, 20)                100       
                                                                 
 dense_12 (Dense)            (None, 20)                420       
                                                                 
 dense_13 (Dense)            (None, 20)                420       
                                                                 
 dense_14 (Dense)            (None, 3)                 63        
                                                                 
Total params: 1,003
Trainable params: 1,003
Non-trainable params: 0
_________________________________________________________________


In [39]:
##Step : 7 : Train the model
##Batch size, epoch and validation split are all hyper parameters
model.fit(X_train, y_train, epochs=195, batch_size=80, validation_split=0.1)

Epoch 1/195
2/2 [==============================] - 1s 153ms/step - loss: 1.0448 - accuracy: 0.3636 - val_loss: 0.9418 - val_accuracy: 0.6429
Epoch 2/195
2/2 [==============================] - 0s 22ms/step - loss: 1.0236 - accuracy: 0.3471 - val_loss: 0.9195 - val_accuracy: 0.6429
Epoch 3/195
2/2 [==============================] - 0s 22ms/step - loss: 1.0049 - accuracy: 0.3884 - val_loss: 0.8977 - val_accuracy: 0.7143
Epoch 4/195
2/2 [==============================] - 0s 23ms/step - loss: 0.9852 - accuracy: 0.4628 - val_loss: 0.8758 - val_accuracy: 0.7143
Epoch 5/195
2/2 [==============================] - 0s 22ms/step - loss: 0.9651 - accuracy: 0.5785 - val_loss: 0.8531 - val_accuracy: 0.7857
Epoch 6/195
2/2 [==============================] - 0s 25ms/step - loss: 0.9463 - accuracy: 0.6777 - val_loss: 0.8290 - val_accuracy: 0.8571
Epoch 7/195
2/2 [==============================] - 0s 23ms/step - loss: 0.9269 - accuracy: 0.7025 - val_loss: 0.8034 - val_accuracy: 0.7857
Epoch 8/195
2/2 [==

In [40]:
##Step : 8 : Get the accuracy of model on testing data
testing=model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1]+'uracy of Model on testing data', testing[1]*100))

1/1 [==============================] - 0s 34ms/step - loss: 0.0265 - accuracy: 1.0000

accuracyuracy of Model on testing data: 100.00%


In [41]:
##Step : 9 : Evaluate our model
from sklearn.metrics import classification_report, confusion_matrix
predictions = np.argmax(model.predict(X_test), axis=1)
Y_test = np.argmax(y_test,axis=1)
#To get confusion matrix
print(confusion_matrix(Y_test,predictions))
#To get values of all evaluation metrics
print(classification_report(Y_test,predictions))

1/1 [==============================] - 0s 115ms/step
[[4 0 0]
 [0 4 0]
 [0 0 7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         7

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

